# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fbg-rails"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-08-28"
  s.description = "Use Fluid Bseline Grid in your Rails apps"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/fbg-rails.rb",
    "test/index.html",
    "unlicense.txt",
    "vendor/assets/images/fbg/24px_grid_bg.gif",
    "vendor/assets/images/fbg/28px_grid_bg.gif",
    "vendor/assets/images/fbg/icons/apple-touch-icon-114x114.png",
    "vendor/assets/images/fbg/icons/apple-touch-icon-57x57.png",
    "vendor/assets/images/fbg/icons/apple-touch-icon-72x72.png",
    "vendor/assets/images/fbg/icons/apple-touch-icon.png",
    "vendor/assets/images/fbg/icons/favicon.ico",
    "vendor/assets/javascripts/respond.min.js",
    "vendor/assets/robot/robots.txt",
    "vendor/assets/stylesheets/fbg.css"
  ]
  s.homepage = "http://github.com/kristianmandrup/fbg-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Fluid Bseline Grid for Rails asset pipeline"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

